apiVersion: deployments.datadoghq.com/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: nginx
spec:
  artifacts:
    - kind: HelmChart
      name: chart
      repository: https://charts.bitnami.com/bitnami/nginx
      version: 13.2.13
    - kind: HelmValues
      name: common
      values:
        image.tag: 1.22.1
    - kind: HelmValues
      name: valuesStaging
      values:
        replicaCount: 1
    - kind: HelmValues
      name: valuesProd
      values:
        replicaCount: 3
  environments:
    - name: staging
      placement:
        staticPlacement:
          namespace: nginx-staging
      requiredArtifacts:
        - chart
        - common
        - valuesStaging
    - name: production
      requiredArtifacts:
        - chart
        - common
        - valuesProd
      constraints:
        - kind: DependsOn
          dependsOn:
            environment: staging
            artifacts:
              - chart
              - common
        - kind: HelmCanary
          helmCanary:
            ttl: 2m
            values:
              replicaCount: 1
