apiVersion: deployments.datadoghq.com/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: nginx
spec:
  artifacts:
    - kind: HelmChart
      name: chart
      repository: https://charts.bitnami.com/bitnami/nginx
      version: 13.2.13
    - kind: HelmValues
      name: common
      values:
        image.tag: 1.22.1
    - kind: HelmValues
      name: valuesStaging
      values:
        replicaCount: 1
    - kind: HelmValues
      name: valuesProd
      values:
        replicaCount: 4
  environments:
    - name: staging
      # requiredArtifacts are all the artifacts that should
      # be deployed to this environment
      requiredArtifacts: ["chart", "common", "valuesStaging"]
      placement:
        # staticPlacement defines an explicit namespace
        # that this should be deployed in
        staticPlacement:
          cluster: staging1
          namespace: nginx-staging
    - name: production
      requiredArtifacts: ["chart", "common", "valuesProd"]
      placement:
        dynamicPlacement:
          selector:
            env: prod
      # constraints defines a set of gates that have to succeed before
      # this environment can be deployed to
      constraints:
        # DependsOn specifies that it's artifacts must have been applied
        # in a lower priotity environment
        - kind: DependsOn
          dependsOn:
            environment: staging
            artifacts:
              - chart
              - common
        - kind: HelmCanary
          helmCanary:
            ttl: 1m
            values:
              replicaCount: 1
