apiVersion: deployments.datadoghq.com/v1alpha1
kind: Application
metadata:
  name: cnab-workflow-worker
  namespace: default
spec:
  ## artifacts define a full list of the images, values & charts that are needed to deploy the application
  ## we can set up watchers on each artifact so that we can trigger deployments when new ones appear
  artifacts:
    - kind: HelmChart
      name: chart
      repository: registry.ddbuild.io/dd-source/domains/eee/cnab/k8s/workflow-worker/chart
    - kind: HelmValues
      name: values-staging
      repository: registry.ddbuild.io/dd-source/domains/eee/cnab/k8s/workflow-worker/values-staging
    - kind: HelmValues
      name: values-production
      repository: registry.ddbuild.io/dd-source/domains/eee/cnab/k8s/workflow-worker/values-production
    - kind: ContainerImage
      name: application-image
      repository: registry.ddbuild.io/dd-source/domains/eee/cnab/k8s/workflow-worker/image
  environments:
    - name: staging
      placement:
        staticPlacement:
          namespace: atlas-staging
      requiredArtifacts:
        - chart
        - values-staging
        - application-image
    - name: production
      requiredArtifacts:
        - chart
        - values-production
        - application-image